name: aaaaxy
base: core20
summary: A nonlinear puzzle platformer taking place in non-Euclidean geometry.
description: |
  AAAAXY is a nonlinear puzzle platformer taking place in non-Euclidean
  geometry.

  Although your general goal is reaching the surprising end of the game,
  you are encouraged to set your own goals while playing. Exploration will
  be rewarded, and secrets await you!

  So jump and run around, and enjoy losing your sense of orientation in
  this World of Wicked Weirdness. Find out what Van Vlijmen will make you
  do. Pick a path, get inside a Klein Bottle, recognize some memes, and by
  all means: don't look up.

  NOTE: to enable joystick/gamepad support, run:
  sudo snap connect aaaaxy:joystick

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

adopt-info: part-aaaaxy

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  part-aaaaxy:
    after:
      - desktop-glib-only
      - alsa-mixin
    plugin: go
    go-channel: stable
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(scripts/version.sh semver)"
    override-build: |
      AAAAXY_GENERATE_ASSETS=false make BINARY="${SNAPCRAFT_PART_INSTALL}/bin/aaaaxy" BUILDTYPE=release
    source: https://github.com/divVerent/aaaaxy
    source-type: git
    build-packages:
      - graphviz
      - imagemagick
      - libasound2-dev
      - libgl-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - pkgconf
    stage-packages:
      - libasound2
      - libgl1
      - libx11-6
      - libxau6

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

environment:
  ALWAYS_USE_PULSEAUDIO: '1'

apps:
  aaaaxy:
    command-chain:
      # Support XDG variables.
      - bin/desktop-launch
      # Keep config and savegames across updates.
      - env XDG_CONFIG_HOME=$SNAP_USER_COMMON/.config XDG_DATA_HOME=$SNAP_USER_COMMON/.local/share
      # Support ALSA.
      - snap/command-chain/alsa-launch
    command: bin/aaaaxy
    plugs:
      - audio-playback
      - joystick
      - opengl
      - x11
