name: Deploy WebAssembly Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: 'sudo apt-get update && sudo apt-get -y install graphviz'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: 'GOOS=js GOARCH=wasm make BUILDTYPE=release'

    - name: Steal/acquire wasm_exec.js
      run: 'cp -v "$(GOOS=js GOARCH=wasm go env GOROOT)/misc/wasm/wasm_exec.js" .'

    - name: Deploy
      env:
        DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
      run: 'tar cvzf - aaaaxy-js-wasm.wasm aaaaxy.html wasm_exec.js | base64 | curl -X POST -d @- "$DEPLOY_URL"'
