name: 100% Single-Platform Test Run

on:
  release:
    types: [ created ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: 'sudo apt-get update && sudo apt-get -y install graphviz libasound2-dev libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev xvfb'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: 'make'

    - name: Fetch Test Cases
      env:
        REGRESSION_TEST_URL: ${{ secrets.REGRESSION_TEST_URL }}
      run: 'curl -o testcases.zip "$REGRESSION_TEST_URL"/100percent-v2.zip'

    - name: Extract Test Cases
      run: 'unzip testcases.zip'

    - name: Test
      run: 'xvfb-run scripts/regression-test-demo.sh linux-amd64 "Your time: 1:01:56\\.450; your speedrun categories: 100%, All Notes and All Paths" ./aaaaxy-debug-linux-amd64 *.dem'

    - name: Archive Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: regression-test-results-100percent-linux-amd64
        path: |
          *.dem.*.log
          *.dem.*.png
