name: Go But With Current Dependencies

on:
  schedule:
    - cron: '51 11 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: 'sudo apt-get update && sudo apt-get -y install graphviz libasound2-dev libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Update
      run: 'make mod-update'

    - name: Build
      run: 'AAAAXY_BUILD_USE_VERSION_FILE=true AAAAXY_GENERATE_ASSETS=true make'

    - name: Vet
      run: 'make vet'
