name: macOS App Bundle Test Run

on:
  pull_request:
  push:
  schedule:
    - cron: '3 17 * * *'
  workflow_dispatch:

jobs:

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: 'brew install imagemagick'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Specific
      run: 'AAAAXY_BUILD_USE_VERSION_FILE=true AAAAXY_ZIPFILE=aaaaxy.zip scripts/binary-release-compile.sh'

    - name: Enable Software Rendering
      run: 'scripts/macos_gl_allow_software.sh packaging/AAAAXY.app/Contents/MacOS/*'

    - name: Test
      run: 'scripts/regression-test-demo.sh darwin-specific "on track for Any%, All Paths and No Teleports" "open -n -W packaging/AAAAXY.app --args" benchmark.dem'

    - name: Build Universal
      run: 'AAAAXY_BUILD_USE_VERSION_FILE=true AAAAXY_ZIPFILE=aaaaxy.zip CGO_ENV_amd64="CGO_ENABLED=1 CC=\"clang -arch x86_64\" CXX=\"clang++ -arch x86_64\"" CGO_ENV_arm64="CGO_ENABLED=1 CC=\"clang -arch arm64\" CXX=\"clang++ -arch arm64\"" scripts/binary-release-compile.sh amd64 arm64'

    - name: Enable Software Rendering
      run: 'scripts/macos_gl_allow_software.sh packaging/AAAAXY.app/Contents/MacOS/*'

    - name: Test
      run: 'scripts/regression-test-demo.sh darwin-universal "on track for Any%, All Paths and No Teleports" "open -n -W packaging/AAAAXY.app --args" benchmark.dem'

    - name: Archive Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: regression-test-results-benchmark-darwin
        path: |
          *.dem.*.log
          *.dem.*.png

