name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: 'sudo apt-get update && sudo apt-get -y install graphviz libasound2-dev libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev xvfb'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build for Windows 32-Bit
      run: 'env GOOS=windows GOARCH=386 make'

    - name: Build for Windows 64-Bit
      run: 'env GOOS=windows GOARCH=amd64 make'

    - name: Build for Linux 64-Bit
      run: 'make'
